version: '3'
services:
  app:
    image: node:8
    tty: true
    working_dir: /app
    ports:
      - "${GRAPH_APP_PORT-8937}:8937"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    restart: on-failure
    entrypoint: node_modules/.bin/gulp
    environment:
      NODE_ENV: development
      PORT: ${GRAPH_APP_PORT-8937}
volumes:
  node_modules: {}
